// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wellbeing_of_mind.Infastructure;

#nullable disable

namespace wellbeing_of_mind.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20240105212546_ChangingAnswers")]
    partial class ChangingAnswers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wellbeing_of_mind.Domain.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("wellbeing_of_mind.Domain.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoiceContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChoiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChoiceContent = "One-two time",
                            ChoiceType = "No Anxiety",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChoiceContent = "Few times",
                            ChoiceType = "Mild Anxiety",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChoiceContent = "Almost every day",
                            ChoiceType = "Severe Anxiety",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            ChoiceContent = "No, I do not",
                            ChoiceType = "No Anxiety",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            ChoiceContent = "Sometimes",
                            ChoiceType = "Mild Anxiety",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            ChoiceContent = "Almost every day",
                            ChoiceType = "Severe Anxiety",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            ChoiceContent = "I do not worry",
                            ChoiceType = "No Anxiety",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            ChoiceContent = "Sometimes",
                            ChoiceType = "Mild Anxiety",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 9,
                            ChoiceContent = "Almost every day",
                            ChoiceType = "Severe Anxiety",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 13,
                            ChoiceContent = "No, I do not",
                            ChoiceType = "No Anxiety",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 14,
                            ChoiceContent = "Sometimes",
                            ChoiceType = "Mild Anxiety",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 15,
                            ChoiceContent = "Almost every day",
                            ChoiceType = "Severe Anxiety",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 16,
                            ChoiceContent = "I do not worry",
                            ChoiceType = "No Anxiety",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 17,
                            ChoiceContent = "Sometimes",
                            ChoiceType = "Mild Anxiety",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 18,
                            ChoiceContent = "Almost every day",
                            ChoiceType = "Severe Anxiety",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 19,
                            ChoiceContent = "I do not",
                            ChoiceType = "No Anxiety",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 20,
                            ChoiceContent = "Sometimes",
                            ChoiceType = "Mild Anxiety",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 21,
                            ChoiceContent = "Almost every day",
                            ChoiceType = "Severe Anxiety",
                            QuestionId = 6
                        });
                });

            modelBuilder.Entity("wellbeing_of_mind.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionContent = "How often have you been bothered by becoming easily annoyed or irritable over the last two weeks ?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 2,
                            QuestionContent = "Do you have trouble relaxing ?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 3,
                            QuestionContent = "How often do you worry about things that might go wrong?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 4,
                            QuestionContent = "Do you experience physical symptoms such as trembling, sweating, or a racing heart when anxious?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 5,
                            QuestionContent = "How often have you been bothered by not being able to stop or control worrying over the last two weeks?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 6,
                            QuestionContent = "How often do you find it difficult to make a decision?",
                            TestId = 1
                        });
                });

            modelBuilder.Entity("wellbeing_of_mind.Domain.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Anxiety Level Test is a quick assessment designed to measure the intensity of anxiety symptoms. It includes questions about worry, restlessness, and physical tension, with respondents rating their experiences on a scale.",
                            Title = "Anxiety level"
                        });
                });

            modelBuilder.Entity("wellbeing_of_mind.Domain.Choice", b =>
                {
                    b.HasOne("wellbeing_of_mind.Domain.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("wellbeing_of_mind.Domain.Question", b =>
                {
                    b.HasOne("wellbeing_of_mind.Domain.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("wellbeing_of_mind.Domain.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("wellbeing_of_mind.Domain.Test", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
